name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]

jobs:
  build:
    uses: itzg/github-workflows/.github/workflows/go-test.yml@main
    with:
      go-version: "1.24.1"
      include-govulncheck: false
